#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/Attendances/Index.cshtml")]
    public partial class _Views_Reports_Attendances_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Reports_Attendances_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Reports\Attendances\Index.cshtml"
  
    ViewBag.Title = "Attendances";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .red.vis-box {\r\n        background-color: #F6D5E7;\r\n        colo" +
"r: #8A0F88;\r\n        border-color: #8A0F88;\r\n    }\r\n</style>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/vis/4.8.2/vis.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"https://cdnjs.cloudflare.com/ajax/libs/vis/4.8.2/vis.min.css\"");

WriteLiteral(" />\r\n\r\n\r\n<div");

WriteLiteral(" class=\"ui huge grey header\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" data-localize=\"Titles.Attendances\"");

WriteLiteral("></span>\r\n</div>\r\n<div");

WriteLiteral(" class=\"ui active large inline loader\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" id=\"visualization\"");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral("></div>\r\n\r\n<script>\r\n    function getAttendance() {\r\n        const url = \"/api/vi" +
"ews/hrm/attendance-view/all\";\r\n\r\n        return window.getAjaxRequest(url);\r\n   " +
" };\r\n\r\n    function show() {\r\n    };\r\n    var employeeId = $(\"#EmployeeSelect\")." +
"val();\r\n\r\n    var getAttendanceAjax = getAttendance(employeeId);\r\n\r\n    getAtten" +
"danceAjax.success(function (msg) {\r\n        if (msg.length) {\r\n            creat" +
"eTimeLine(msg);\r\n        };\r\n    });\r\n\r\n</script>\r\n<script>\r\n    function create" +
"TimeLine(data) {\r\n        const employeeGroup = window.Enumerable.From(data).Gro" +
"upBy(function (x) { return x.EmployeeId; }).ToArray();\r\n        const min = wind" +
"ow.Enumerable.From(data).MinBy(function (x) { return x.AttendanceDate; }).Attend" +
"anceDate;\r\n        const max = window.Enumerable.From(data).MaxBy(function (x) {" +
" return x.AttendanceDate; }).AttendanceDate;\r\n\r\n\r\n        const groups = new win" +
"dow.vis.DataSet();\r\n\r\n        for (let g = 0; g < employeeGroup.length; g++) {\r\n" +
"            groups.add(\r\n                {\r\n                    id: employeeGrou" +
"p[g].source[0].EmployeeId,\r\n                    content: employeeGroup[g].source" +
"[0].Employee,\r\n                    title: employeeGroup[g].source[0].Photo\r\n    " +
"            });\r\n        };\r\n\r\n        // create a dataset with items\r\n        c" +
"onst items = new window.vis.DataSet();\r\n\r\n        for (let i = 0; i < data.lengt" +
"h / employeeGroup.length; i++) {\r\n            const content = data[i].WasPresent" +
" ? \"P\" : \"A\";\r\n            const className = data[i].WasPresent ? \"\" : \"red\";\r\n\r" +
"\n            items.add({\r\n                id: i,\r\n                group: data[i]" +
".EmployeeId,\r\n                content: content,\r\n                start: data[i]." +
"AttendanceDate,\r\n                type: \'box\',\r\n                className: classN" +
"ame\r\n            });\r\n        };\r\n\r\n        // create visualization\r\n        con" +
"st container = document.getElementById(\'visualization\');\r\n        $(container).h" +
"tml(\"\");\r\n\r\n        const options = {\r\n            groupOrder: \'content\',  // gr" +
"oupOrder can be a property name or a sorting function\r\n            orientation: " +
"{\r\n                axis: \'both\',\r\n                item: \'top\'\r\n            },\r\n " +
"           min: min,\r\n            max: max,\r\n            zoomMin: 1000 * 60 * 60" +
" * 24,             // one day in milliseconds\r\n            zoomMax: 1000 * 60 * " +
"60 * 24 * 31 * 3     // about three months in milliseconds\r\n        };\r\n\r\n      " +
"  const timeline = new window.vis.Timeline(container);\r\n        timeline.setOpti" +
"ons(options);\r\n        timeline.setGroups(groups);\r\n        timeline.setItems(it" +
"ems);\r\n\r\n        const labels = $(\".vis-label\");\r\n        labels.each(function (" +
") {\r\n            const el = $(this);\r\n            const inner = el.find(\".vis-in" +
"ner\");\r\n\r\n            const photo = el.attr(\"title\");\r\n            el.removeAttr" +
"(\"title\");\r\n\r\n            const header = $(\"<div class=\'ui big grey header\' />\")" +
";\r\n            header.html(inner.html());\r\n\r\n            const img = $(\"<img />\"" +
");\r\n\r\n            img.attr(\"class\", \"ui small centered rounded circular bordered" +
" image\");\r\n            img.attr(\"title\", inner.html());\r\n            img.attr(\"s" +
"rc\", \"/api/core/attachment/document/400/400/\" + photo);\r\n\r\n            inner.add" +
"Class(\"ui attached secondary segment\");\r\n            inner.prepend(img);\r\n      " +
"  });\r\n\r\n        $(\".loader\").removeClass(\"active\");\r\n        $(container).fadeI" +
"n(1000);\r\n    };\r\n\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
