#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Verification/Resignations/Index.cshtml")]
    public partial class _Views_Verification_Resignations_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Verification_Resignations_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Verification\Resignations\Index.cshtml"
  
    ViewBag.Title = "Resignations";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral(@"
<script>
    var scrudFactory = new Object();

    scrudFactory.title = ""Verify Resignations"";

    scrudFactory.viewAPI = ""/api/views/hrm/resignation-verification-scrud-view"";
    scrudFactory.viewTableName = ""hrm.resignation_verification_scrud_view"";

    scrudFactory.formAPI = ""/api/forms/hrm/resignation"";
    scrudFactory.formTableName = ""hrm.resignations"";

    scrudFactory.hasVerfication = true;
    scrudFactory.excludedColumns = [""Photo""];
    $.get('/ScrudFactory/View.html', function (view) {
        $(""#ScrudFactoryView"").html(view);
        $.cachedScript(""/assets/js/scrudfactory-view.js"");
    });
</script>

<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
