#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Attendance/Index.cshtml")]
    public partial class _Views_Tasks_Attendance_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Attendance_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Attendance\Index.cshtml"
  
    ViewBag.Title = "Attendance";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"Attendance\"");

WriteLiteral(" data-ng-controller=\"AttendanceController\"");

WriteLiteral(" data-ng-cloak");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Attenance</div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui form bpad16\"");

WriteLiteral(" style=\"width: 440px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                <label>For Date</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DateInputDate\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                <label>&nbsp;</label>\r\n                <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" data-ng-click=\"show();\"");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Show</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui link cards\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"attendance card\"");

WriteLiteral(" data-ng-repeat=\"employee in employees\"");

WriteLiteral(" data-attendance-id=\"{{employee.Attendance.AttendanceId}}\"");

WriteLiteral(" data-employee-id=\"{{employee.EmployeeId}}\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"image\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" data-ng-src=\"/api/core/attachment/document/400/200/{{employee.Photo}}\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">{{employee.EmployeeCode}} ({{employee.EmployeeName}})</div>\r\n                <di" +
"v");

WriteLiteral(" class=\"meta\"");

WriteLiteral(">\r\n                    <a>{{employee.CurrentDepartment}}</a>\r\n                </d" +
"iv>\r\n                <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui toggle vpad8 checkbox\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"PresentCheckBox{{employee.EmployeeId}}\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral("\r\n                                   data-employee-id=\"{{employee.EmployeeId}}\"");

WriteLiteral("\r\n                                   data-ng-model=\"employee.Attendance.WasPresen" +
"t\"");

WriteLiteral("\r\n                                   onclick=\"toggleAttendance(this);\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"PresentCheckBox{{employee.EmployeeId}}\"");

WriteLiteral(" class=\"pointer\"");

WriteLiteral(">Is Present</label>\r\n                        </div>\r\n                        <div" +
"");

WriteLiteral(" class=\"three fields present\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Check In Time</label>\r\n                " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"check-in time\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.CheckInTime\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Check Out Time</label>\r\n               " +
"                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"check-out time\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.CheckOutTime\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Overtime Hours</label>\r\n               " +
"                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"overtime-hours decimal\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.OvertimeHours\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"vpad8 absent\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Reason</label>\r\n                       " +
"         <textarea");

WriteLiteral(" rows=\"1\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.ReasonForAbsenteeism\"");

WriteLiteral("></textarea>\r\n                            </div>\r\n                        </div>\r" +
"\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"extra content\"");

WriteLiteral(">\r\n                <span>\r\n                    <i");

WriteLiteral(" class=\"user icon\"");

WriteLiteral("></i>\r\n                    {{employee.Office}}\r\n                </span>\r\n        " +
"    </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"updateAll()\"");

WriteLiteral(" class=\"ui teal button\"");

WriteLiteral(">Update All</a>\r\n    </div>\r\n    {{success()}}\r\n</div>\r\n<script>\r\n    $(\"#DateInp" +
"utDate\").val(window.today);\r\n\r\n    frapidApp.controller(\"AttendanceController\", " +
"function ($timeout, $scope, $sce, $window) {\r\n        function requestEmployees(" +
") {\r\n            const url = \"/api/views/hrm/employee-view/all\";\r\n            re" +
"turn window.getAjaxRequest(url);\r\n        };\r\n\r\n        function requestAttendan" +
"ce(date) {\r\n            const url = \"/api/forms/hrm/attendances/get-where/-1/\";\r" +
"\n\r\n            const filters = [];\r\n            filters.push(window.getAjaxColum" +
"nFilter(\"WHERE\", \"AttendanceDate\", \"System.DateTime\", window.FilterConditions.Is" +
"EqualTo, date));\r\n            const data = JSON.stringify(filters);\r\n\r\n         " +
"   return window.getAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n        $scop" +
"e.show = function() {\r\n            const requestEmployeesAjax = requestEmployees" +
"();\r\n\r\n            requestEmployeesAjax.success(function (employees) {\r\n        " +
"        const date = window.parseLocalizedDate($(\"#DateInputDate\").val());\r\n\r\n  " +
"              const requestAttendanceAjax = requestAttendance(date);\r\n\r\n        " +
"        requestAttendanceAjax.success(function (attendance) {\r\n                 " +
"   $.each(employees, function (i, v) {\r\n                        var employee = v" +
";\r\n\r\n                        const a = $window.Enumerable.From(attendance)\r\n    " +
"                        .Where(function (x) { return x.EmployeeId === employee.E" +
"mployeeId }).FirstOrDefault() || new Object();\r\n\r\n                        a.Chec" +
"kInTime = (a.CheckInTime || \"\").toString().toTime();\r\n                        a." +
"CheckOutTime = (a.CheckOutTime || \"\").toString().toTime();\r\n                    " +
"    employees[i].Attendance = a;\r\n                    });\r\n\r\n                   " +
" $scope.$apply(function () {\r\n                        $scope.employees = employe" +
"es;\r\n                    });\r\n                });\r\n            });\r\n        };\r\n" +
"\r\n        $scope.show();\r\n\r\n        $scope.success = function() {\r\n            $" +
"timeout(function() {\r\n                const checkboxes = $(\":checkbox\");\r\n      " +
"          checkboxes.each(function() {\r\n                    toggleAttendance(thi" +
"s);\r\n                });\r\n\r\n                $window.loadDatepicker();\r\n         " +
"       $window.setRegionalFormat();\r\n                $(\"#Attendance\").fadeIn(500" +
");\r\n            }, 500);\r\n        };\r\n    });\r\n\r\n    function toggleAttendance(s" +
"ender) {\r\n        sender = $(sender);\r\n        const isPresent = sender.is(\":che" +
"cked\");\r\n        const employeeId = sender.attr(\"data-employee-id\");\r\n        co" +
"nst el = $(\'.card[data-employee-id=\"\' + employeeId + \'\"]\');\r\n\r\n        if (isPre" +
"sent) {\r\n            el.find(\".absent\").hide();\r\n            el.find(\".present\")" +
".fadeIn(200);\r\n        } else {\r\n            el.find(\".present\").hide();\r\n      " +
"      el.find(\".absent\").fadeIn(200);\r\n        };\r\n    };\r\n\r\n    function getTim" +
"e(el) {\r\n        const time = el.val();\r\n        const regex = /^\\s*([01]?\\d|2[0" +
"-3]):?([0-5]\\d)\\s*$/;\r\n\r\n        if (regex.test(time)) {\r\n            return tim" +
"e;\r\n        };\r\n\r\n        return null;\r\n    };\r\n\r\n    function getAttendance(car" +
"d) {\r\n        const attendanceId = (card.attr(\"data-attendance-id\") || null);\r\n " +
"       const employeeId = card.attr(\"data-employee-id\");\r\n        const isPresen" +
"t = card.find(\"input:checkbox\").is(\":checked\");\r\n        const checkInTime = win" +
"dow.getTime(card.find(\"input.check-in\"));\r\n        const checkOutTime = window.g" +
"etTime(card.find(\"input.check-out\"));\r\n        const overTimeHours = card.find(\"" +
"input.overtime-hours\").val();\r\n        const reason = card.find(\"textarea\").val(" +
");\r\n\r\n        const attendance = new Object();\r\n        attendance.attendance_id" +
" = attendanceId;\r\n        attendance.office_id = window.metaView.OfficeId;\r\n    " +
"    attendance.employee_id = employeeId;\r\n        attendance.attendance_date = w" +
"indow.parseLocalizedDate($(\"#DateInputDate\").val());\r\n        attendance.was_pre" +
"sent = isPresent;\r\n        attendance.check_in_time = isPresent ? checkInTime : " +
"null;\r\n        attendance.check_out_time = isPresent ? checkOutTime : null;\r\n   " +
"     attendance.overtime_hours = overTimeHours;\r\n        attendance.was_absent =" +
" !attendance.was_present;\r\n        attendance.reason_for_absenteeism = attendanc" +
"e.was_absent ? reason : null;\r\n        attendance.audit_user_id = window.userId;" +
"\r\n        attendance.audit_ts = new Date();\r\n\r\n        return attendance;\r\n    }" +
";\r\n\r\n    function request(attendnaces) {\r\n        const url = \"/api/forms/hrm/at" +
"tendance/bulk-import\";\r\n        const data = JSON.stringify(attendnaces);\r\n\r\n   " +
"     return window.getAjaxRequest(url, \"POST\", data);\r\n    };\r\n\r\n    function se" +
"ndRequest(attendances) {\r\n        const ajax = request(attendances);\r\n\r\n        " +
"ajax.success(function () {\r\n            window.location = window.location.pathna" +
"me;\r\n        });\r\n\r\n    };\r\n\r\n    function updateAll() {\r\n        const cards = " +
"$(\".attendance.card\");\r\n        var attendances = [];\r\n\r\n        cards.each(func" +
"tion () {\r\n            const el = $(this);\r\n            attendances.push(getAtte" +
"ndance(el));\r\n        });\r\n\r\n        sendRequest(attendances);\r\n    };\r\n</script" +
">\r\n");

        }
    }
}
#pragma warning restore 1591
