#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Attendance/Index.cshtml")]
    public partial class _Views_Tasks_Attendance_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Attendance_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Attendance\Index.cshtml"
  
    ViewBag.Title = "Attendance";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"Attendance\"");

WriteLiteral(" data-ng-controller=\"AttendanceController\"");

WriteLiteral(" data-ng-cloak");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Attenance</div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui form bpad16\"");

WriteLiteral(" style=\"width: 440px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                <label>For Date</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DateInputDate\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                <label>&nbsp;</label>\r\n                <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" data-ng-click=\"show();\"");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">Show</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui link cards\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"attendance card\"");

WriteLiteral(" data-ng-repeat=\"employee in employees\"");

WriteLiteral(" data-attendance-id=\"{{employee.Attendance.AttendanceId}}\"");

WriteLiteral(" data-employee-id=\"{{employee.EmployeeId}}\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"image\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" data-ng-src=\"/api/core/attachment/document/400/200/{{employee.Photo}}\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">{{employee.EmployeeCode}} ({{employee.EmployeeName}})</div>\r\n                <di" +
"v");

WriteLiteral(" class=\"meta\"");

WriteLiteral(">\r\n                    <a>{{employee.CurrentDepartment}}</a>\r\n                </d" +
"iv>\r\n                <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui toggle vpad8 checkbox\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"PresentCheckBox{{employee.EmployeeId}}\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral("\r\n                                   data-employee-id=\"{{employee.EmployeeId}}\"");

WriteLiteral("\r\n                                   data-ng-model=\"employee.Attendance.WasPresen" +
"t\"");

WriteLiteral("\r\n                                   onclick=\"toggleAttendance(this);\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"PresentCheckBox{{employee.EmployeeId}}\"");

WriteLiteral(" class=\"pointer\"");

WriteLiteral(">Is Present</label>\r\n                        </div>\r\n                        <div" +
"");

WriteLiteral(" class=\"three fields present\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Check In Time</label>\r\n                " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"check-in time\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.CheckInTime\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Check Out Time</label>\r\n               " +
"                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"check-out time\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.CheckOutTime\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Overtime Hours</label>\r\n               " +
"                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"overtime-hours decimal\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.OvertimeHours\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"vpad8 absent\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ui field\"");

WriteLiteral(">\r\n                                <label>Reason</label>\r\n                       " +
"         <textarea");

WriteLiteral(" rows=\"1\"");

WriteLiteral(" data-ng-model=\"employee.Attendance.ReasonForAbsenteeism\"");

WriteLiteral("></textarea>\r\n                            </div>\r\n                        </div>\r" +
"\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"extra content\"");

WriteLiteral(">\r\n                <span>\r\n                    <i");

WriteLiteral(" class=\"user icon\"");

WriteLiteral("></i>\r\n                    {{employee.Office}}\r\n                </span>\r\n        " +
"    </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"vpad8\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"updateAll()\"");

WriteLiteral(" class=\"ui teal button\"");

WriteLiteral(">Update All</a>\r\n    </div>\r\n    {{success()}}\r\n</div>\r\n<script>\r\n    $(\"#DateInp" +
"utDate\").val(window.today);\r\n\r\n    frapidApp.controller(\"AttendanceController\", " +
"function ($timeout, $scope, $sce, $window) {\r\n        function requestEmployees(" +
") {\r\n            var url = \"/api/views/hrm/employee-view/all\";\r\n            retu" +
"rn window.getAjaxRequest(url);\r\n        };\r\n\r\n        function requestAttendance" +
"(date) {\r\n            var url = \"/api/forms/hrm/attendances/get-where/-1/\";\r\n\r\n " +
"           var filters = [];\r\n            filters.push(window.getAjaxColumnFilte" +
"r(\"WHERE\", \"attendance_date\", \"System.DateTime\", window.FilterConditions.IsEqual" +
"To, date));\r\n            var data = JSON.stringify(filters);\r\n\r\n            retu" +
"rn window.getAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n        $scope.show " +
"= function() {\r\n            var requestEmployeesAjax = requestEmployees();\r\n\r\n  " +
"          requestEmployeesAjax.success(function (employees) {\r\n                v" +
"ar date = window.parseLocalizedDate($(\"#DateInputDate\").val());\r\n\r\n             " +
"   var requestAttendanceAjax = requestAttendance(date);\r\n\r\n                reque" +
"stAttendanceAjax.success(function (attendance) {\r\n                    $.each(emp" +
"loyees, function (i, v) {\r\n                        var employee = v;\r\n\r\n        " +
"                var a = $window.Enumerable.From(attendance)\r\n                   " +
"         .Where(function (x) { return x.EmployeeId === employee.EmployeeId }).Fi" +
"rstOrDefault() || new Object();\r\n\r\n                        a.CheckInTime = (a.Ch" +
"eckInTime || \"\").toString().toTime();\r\n                        a.CheckOutTime = " +
"(a.CheckOutTime || \"\").toString().toTime();\r\n                        employees[i" +
"].Attendance = a;\r\n                    });\r\n\r\n                    $scope.$apply(" +
"function () {\r\n                        $scope.employees = employees;\r\n          " +
"          });\r\n                });\r\n            });\r\n        };\r\n\r\n        $scop" +
"e.show();\r\n\r\n        $scope.success = function() {\r\n            $timeout(functio" +
"n() {\r\n                var checkboxes = $(\":checkbox\");\r\n                checkbo" +
"xes.each(function() {\r\n                    toggleAttendance(this);\r\n            " +
"    });\r\n\r\n                $window.loadDatepicker();\r\n                $window.se" +
"tRegionalFormat();\r\n                $(\"#Attendance\").fadeIn(500);\r\n            }" +
", 500);\r\n        };\r\n    });\r\n\r\n    function toggleAttendance(sender) {\r\n       " +
" sender = $(sender);\r\n        var isPresent = sender.is(\":checked\");\r\n        va" +
"r employeeId = sender.attr(\"data-employee-id\");\r\n        var el = $(\'.card[data-" +
"employee-id=\"\' + employeeId + \'\"]\');\r\n\r\n        if (isPresent) {\r\n            el" +
".find(\".absent\").hide();\r\n            el.find(\".present\").fadeIn(200);\r\n        " +
"} else {\r\n            el.find(\".present\").hide();\r\n            el.find(\".absent\"" +
").fadeIn(200);\r\n        };\r\n    };\r\n\r\n    function getTime(el) {\r\n        var ti" +
"me = el.val();\r\n        var regex = /^\\s*([01]?\\d|2[0-3]):?([0-5]\\d)\\s*$/;\r\n\r\n  " +
"      if (regex.test(time)) {\r\n            return time;\r\n        };\r\n\r\n        r" +
"eturn null;\r\n    };\r\n\r\n    function getAttendance(card) {\r\n        var attendanc" +
"eId = (card.attr(\"data-attendance-id\") || null);\r\n        var employeeId = card." +
"attr(\"data-employee-id\");\r\n        var isPresent = card.find(\"input:checkbox\").i" +
"s(\":checked\");\r\n        var checkInTime = window.getTime(card.find(\"input.check-" +
"in\"));\r\n        var checkOutTime = window.getTime(card.find(\"input.check-out\"));" +
"\r\n        var overTimeHours = card.find(\"input.overtime-hours\").val();\r\n        " +
"var reason = card.find(\"textarea\").val();\r\n\r\n        var attendance = new Object" +
"();\r\n        attendance.attendance_id = attendanceId;\r\n        attendance.office" +
"_id = window.metaView.OfficeId;\r\n        attendance.employee_id = employeeId;\r\n " +
"       attendance.attendance_date = window.parseLocalizedDate($(\"#DateInputDate\"" +
").val());\r\n        attendance.was_present = isPresent;\r\n        attendance.check" +
"_in_time = isPresent ? checkInTime : null;\r\n        attendance.check_out_time = " +
"isPresent ? checkOutTime : null;\r\n        attendance.overtime_hours = overTimeHo" +
"urs;\r\n        attendance.was_absent = !attendance.was_present;\r\n        attendan" +
"ce.reason_for_absenteeism = attendance.was_absent ? reason : null;\r\n        atte" +
"ndance.audit_user_id = window.userId;\r\n        attendance.audit_ts = new Date();" +
"\r\n\r\n        return attendance;\r\n    };\r\n\r\n    function request(attendnaces) {\r\n " +
"       var url = \"/api/forms/hrm/attendance/bulk-import\";\r\n        var data = JS" +
"ON.stringify(attendnaces);\r\n\r\n        return window.getAjaxRequest(url, \"POST\", " +
"data);\r\n    };\r\n\r\n    function sendRequest(attendances) {\r\n        var ajax = re" +
"quest(attendances);\r\n\r\n        ajax.success(function () {\r\n            window.lo" +
"cation = window.location.pathname;\r\n        });\r\n\r\n    };\r\n\r\n    function update" +
"All() {\r\n        var cards = $(\".attendance.card\");\r\n        var attendances = [" +
"];\r\n\r\n        cards.each(function () {\r\n            var el = $(this);\r\n         " +
"   attendances.push(getAttendance(el));\r\n        });\r\n\r\n        sendRequest(atte" +
"ndances);\r\n    };\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
