#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Employees/Experiences.cshtml")]
    public partial class _Views_Tasks_Employees_Experiences_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Employees_Experiences_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Employees\Experiences.cshtml"
  
    ViewBag.Title = "Expriences";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"Exp" +
"riences\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/hrm/employee-experience-scru" +
"d-view\";\r\n    scrudFactory.viewTableName = \"hrm.employee_experience_scrud_view\";" +
"\r\n\r\n    scrudFactory.formAPI = \"/api/forms/hrm/employee-experiences\";\r\n    scrud" +
"Factory.formTableName = \"hrm.employee_experiences\";\r\n\r\n    scrudFactory.excluded" +
"Columns = [\"AuditUserId\", \"AuditTs\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n " +
"   scrudFactory.allowEdit = true;\r\n\r\n    scrudFactory.live = \"Title\";\r\n\r\n    scr" +
"udFactory.back = {\r\n        Title: \"Employee\",\r\n        Url: \"/dashboard/hrm/tas" +
"ks/employee-info/\" + getQueryStringByName(\"EmployeeId\")\r\n    };\r\n\r\n    scrudFact" +
"ory.layout = [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n        " +
"        [\"EmployeeExperienceId\", \"EmployeeId\"],\r\n                [\"OrganizationN" +
"ame\", \"Title\"],\r\n                [\"StartedOn\", \"EndedOn\"],\r\n                [\"De" +
"tails\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n\r\n    scrudFactory.keys = [\r\n      " +
"  {\r\n            property: \"EmployeeId\",\r\n            url: \'/api/views/hrm/emplo" +
"yee-view/display-fields\',\r\n            data: null,\r\n            valueField: \"Key" +
"\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n    $.get(\'/ScrudFact" +
"ory/View.html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', func" +
"tion (form) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#S" +
"crudFactoryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scrudfacto" +
"ry-view.js\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n " +
"       });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
