#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Employees/IdentificationDetails.cshtml")]
    public partial class _Views_Tasks_Employees_IdentificationDetails_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Employees_IdentificationDetails_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Employees\IdentificationDetails.cshtml"
  
    ViewBag.Title = "Identification Details";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"Ide" +
"ntification Details\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/hrm/employee-ide" +
"ntification-detail-scrud-view\";\r\n    scrudFactory.viewTableName = \"hrm.employee_" +
"identification_detail_scrud_view\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/hrm" +
"/employee-identification-details\";\r\n    scrudFactory.formTableName = \"hrm.employ" +
"ee_identification_details\";\r\n\r\n    scrudFactory.excludedColumns = [\"AuditUserId\"" +
", \"AuditTs\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdi" +
"t = true;\r\n\r\n    scrudFactory.live = \"Title\";\r\n\r\n    scrudFactory.back = {\r\n    " +
"    Title: \"Employee\",\r\n        Url: \"/dashboard/hrm/tasks/employee-info/\" + get" +
"QueryStringByName(\"EmployeeId\")\r\n    };\r\n\r\n    scrudFactory.layout = [\r\n        " +
"{\r\n            tab: \"\",\r\n            fields: [\r\n            ]\r\n        }\r\n    ];" +
"\r\n\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            property: \"EmployeeId\",\r" +
"\n            url: \'/api/views/hrm/employee-view/display-fields\',\r\n            da" +
"ta: null,\r\n            valueField: \"Key\",\r\n            textField: \"Value\"\r\n     " +
"   },\r\n        {\r\n            property: \"IdentificationTypeCode\",\r\n            u" +
"rl: \'/api/forms/hrm/identification-types/lookup-fields\',\r\n            data: null" +
",\r\n            valueField: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n  " +
"  ];\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view) {\r\n        $.get(" +
"\'/ScrudFactory/Form.html\', function (form) {\r\n            $(\"#ScrudFactoryView\")" +
".html(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n            $.cach" +
"edScript(\"/assets/js/scrudfactory-view.js\");\r\n            $.cachedScript(\"/asset" +
"s/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral(@"></div>

<script>
    function identificationTypeExpires(filters) {
        var url = ""/api/forms/hrm/identification-types/get-where/1"";
        var data = JSON.stringify(filters);
        return window.getAjaxRequest(url, ""POST"", data, false);
    };

    function checkIfExpires() {
        var value = $(""#identification_type_code"").getSelectedValue();

        if (!value) {
            return;
        };

        var filters = [];
        filters.push(window.getAjaxColumnFilter(""WHERE"", ""identification_type_code"", ""string"", window.FilterConditions.IsEqualTo, value));

        var ajaxIdentificationTypeExpires = identificationTypeExpires(filters);

        ajaxIdentificationTypeExpires.success(function (msg) {
            var canExpire = msg[0].CanExpire;


            if (!canExpire) {
                $(""#expires_on"").val("""");
            };

            $(""#expires_on"").prop(""disabled"", !canExpire);
        });
    };

    $(document).on(""formready"", function () {
        checkIfExpires();

        $(""#identification_type_code"").change(function () {
            checkIfExpires();
        });;
    });
</script>");

        }
    }
}
#pragma warning restore 1591
