#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Employees/Info.cshtml")]
    public partial class _Views_Tasks_Employees_Info_cshtml : System.Web.Mvc.WebViewPage<MixERP.HRM.ViewModels.EmployeeInfo>
    {
        public _Views_Tasks_Employees_Info_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Employees\Info.cshtml"
  
    ViewBag.Title = "Employee Info " + Model.Details.EmployeeName;
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui attached padded segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui purple header\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 282), Tuple.Create("\"", 365)
, Tuple.Create(Tuple.Create("", 288), Tuple.Create("/dashboard/hrm/services/attachments/", 288), true)
            
            #line 11 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 324), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 324), false)
, Tuple.Create(Tuple.Create("", 344), Tuple.Create("?Width=200&Height=200", 344), true)
);

WriteLiteral("\r\n                 class=\"ui circular image\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 410), Tuple.Create("\"", 443)
            
            #line 12 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 416), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeName
            
            #line default
            #line hidden
, 416), false)
);

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 14 "..\..\Views\Tasks\Employees\Info.cshtml"
           Write(Model.Details.EmployeeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"sub header\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\Tasks\Employees\Info.cshtml"
               Write(Model.Details.EmployeeType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"bpad8\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"/dashboard/hrm/tasks/employees\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Employees</a>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 871), Tuple.Create("\"", 968)
, Tuple.Create(Tuple.Create("", 878), Tuple.Create("/dashboard/hrm/tasks/employees/identification-details?EmployeeId=", 878), true)
            
            #line 25 "..\..\Views\Tasks\Employees\Info.cshtml"
           , Tuple.Create(Tuple.Create("", 943), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 943), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Identification Details</a>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1040), Tuple.Create("\"", 1130)
, Tuple.Create(Tuple.Create("", 1047), Tuple.Create("/dashboard/hrm/tasks/employees/social-networks?EmployeeId=", 1047), true)
            
            #line 26 "..\..\Views\Tasks\Employees\Info.cshtml"
   , Tuple.Create(Tuple.Create("", 1105), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1105), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Social Networks</a>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1195), Tuple.Create("\"", 1281)
, Tuple.Create(Tuple.Create("", 1202), Tuple.Create("/dashboard/hrm/tasks/employees/experiences?EmployeeId=", 1202), true)
            
            #line 27 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 1256), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1256), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Experiences</a>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1342), Tuple.Create("\"", 1431)
, Tuple.Create(Tuple.Create("", 1349), Tuple.Create("/dashboard/hrm/tasks/employees/qualifications?EmployeeId=", 1349), true)
            
            #line 28 "..\..\Views\Tasks\Employees\Info.cshtml"
  , Tuple.Create(Tuple.Create("", 1406), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1406), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Qualifications</a>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1495), Tuple.Create("\"", 1587)
, Tuple.Create(Tuple.Create("", 1502), Tuple.Create("/dashboard/hrm/tasks/employees/leave-application?EmployeeId=", 1502), true)
            
            #line 29 "..\..\Views\Tasks\Employees\Info.cshtml"
     , Tuple.Create(Tuple.Create("", 1562), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1562), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Leave Application</a>\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"ui attached tabular menu\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"active item\"");

WriteLiteral(" data-tab=\"general-info-tab\"");

WriteLiteral(">General Information</a>\r\n            <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"identification-tab\"");

WriteLiteral(">Identification Details</a>\r\n            <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"social-networks-tab\"");

WriteLiteral(">Social Networks</a>\r\n            <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"experiences-tab\"");

WriteLiteral(">Experiences</a>\r\n            <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"qualifications-tab\"");

WriteLiteral(">Qualifications</a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui active tab attached segment\"");

WriteLiteral(" data-tab=\"general-info-tab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"five wide column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui segment\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui large header\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 45 "..\..\Views\Tasks\Employees\Info.cshtml"
                       Write(Model.Details.EmployeeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2533), Tuple.Create("\"", 2596)
, Tuple.Create(Tuple.Create("", 2540), Tuple.Create("/dashboard/hrm/services/attachments/", 2540), true)
            
            #line 47 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2576), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 2576), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2648), Tuple.Create("\"", 2731)
, Tuple.Create(Tuple.Create("", 2654), Tuple.Create("/dashboard/hrm/services/attachments/", 2654), true)
            
            #line 48 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2690), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 2690), false)
, Tuple.Create(Tuple.Create("", 2710), Tuple.Create("?Height=300&Width=272", 2710), true)
);

WriteLiteral(" class=\"ui image\"");

WriteAttribute("alt", Tuple.Create("\r\n                                 alt=\"", 2749), Tuple.Create("\"", 2816)
            
            #line 49 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2789), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeName
            
            #line default
            #line hidden
, 2789), false)
);

WriteLiteral(" />\r\n                        </a>\r\n                        <br />\r\n              " +
"          <table");

WriteLiteral(" class=\"ui striped definition table\"");

WriteLiteral(@">
                            <tbody>
                                <tr>
                                    <td>
                                        Email Address
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"mail icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3319), Tuple.Create("\"", 3360)
, Tuple.Create(Tuple.Create("", 3326), Tuple.Create("mailto:", 3326), true)
            
            #line 60 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 3333), Tuple.Create<System.Object, System.Int32>(Model.Details.EmailAddress
            
            #line default
            #line hidden
, 3333), false)
);

WriteLiteral(">");

            
            #line 60 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                Write(Model.Details.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Website
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"world icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3801), Tuple.Create("\"", 3830)
            
            #line 69 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 3808), Tuple.Create<System.Object, System.Int32>(Model.Details.Website
            
            #line default
            #line hidden
, 3808), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                    Write(Model.Details.Website);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Blog
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"world icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4279), Tuple.Create("\"", 4305)
            
            #line 78 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 4286), Tuple.Create<System.Object, System.Int32>(Model.Details.Blog
            
            #line default
            #line hidden
, 4286), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                 Write(Model.Details.Blog);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Home Phone
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"phone icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4757), Tuple.Create("\"", 4792)
, Tuple.Create(Tuple.Create("", 4764), Tuple.Create("tel:", 4764), true)
            
            #line 87 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 4768), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneHome
            
            #line default
            #line hidden
, 4768), false)
);

WriteLiteral(">");

            
            #line 87 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                          Write(Model.Details.PhoneHome);

            
            #line default
            #line hidden
WriteLiteral(@"</a>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Cell Phone
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"mobile icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5236), Tuple.Create("\"", 5271)
, Tuple.Create(Tuple.Create("", 5243), Tuple.Create("tel:", 5243), true)
            
            #line 97 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 5247), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneCell
            
            #line default
            #line hidden
, 5247), false)
);

WriteLiteral(">");

            
            #line 97 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                          Write(Model.Details.PhoneCell);

            
            #line default
            #line hidden
WriteLiteral(@"</a>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Phone (Office Extension)
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"phone icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5728), Tuple.Create("\"", 5774)
, Tuple.Create(Tuple.Create("", 5735), Tuple.Create("tel:", 5735), true)
            
            #line 107 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 5739), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneOfficeExtension
            
            #line default
            #line hidden
, 5739), false)
);

WriteLiteral(">");

            
            #line 107 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                     Write(Model.Details.PhoneOfficeExtension);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                                    </td>\r\n                              " +
"  </tr>\r\n                                <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                    <td>\r\n                                    " +
"    Emergency Phone\r\n                                    </td>\r\n                " +
"                    <td>\r\n                                        <i");

WriteLiteral(" class=\"red phone icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6254), Tuple.Create("\"", 6294)
, Tuple.Create(Tuple.Create("", 6261), Tuple.Create("tel:", 6261), true)
            
            #line 117 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 6265), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneEmergency
            
            #line default
            #line hidden
, 6265), false)
);

WriteLiteral(">");

            
            #line 117 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                               Write(Model.Details.PhoneEmergency);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </td>\r\n                                " +
"</tr>\r\n                                <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                    <td>\r\n                                    " +
"    Emergency Phone 2\r\n                                    </td>\r\n              " +
"                      <td>\r\n                                        <i");

WriteLiteral(" class=\"red phone icon\"");

WriteLiteral("></i>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6768), Tuple.Create("\"", 6809)
, Tuple.Create(Tuple.Create("", 6775), Tuple.Create("tel:", 6775), true)
            
            #line 126 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 6779), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneEmergency2
            
            #line default
            #line hidden
, 6779), false)
);

WriteLiteral(">");

            
            #line 126 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                Write(Model.Details.PhoneEmergency2);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </td>\r\n                                " +
"</tr>\r\n                                <tr>\r\n                                   " +
" <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        User\r\n                                " +
"    </td>\r\n                                    <td>\r\n                           " +
"             <i");

WriteLiteral(" class=\"user icon\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                        ");

            
            #line 135 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                            </tbody>\r\n                        </table>\r\n     " +
"               </div>\r\n\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"eleven wide column\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"ui striped definition table\"");

WriteLiteral(">\r\n                        <tbody>\r\n                            <tr>\r\n           " +
"                     <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Joined On\r\n                               " +
" </td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 7865), Tuple.Create("\"", 7907)
            
            #line 150 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 7873), Tuple.Create<System.Object, System.Int32>(Model.Details.JoinedOn.ToString()
            
            #line default
            #line hidden
, 7873), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 151 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.JoinedOn);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Office\r\n                                </" +
"td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 159 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.Office);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Gender\r\n                                </" +
"td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 167 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.GenderName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Marital Status\r\n                          " +
"      </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 175 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.MaritalStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Employee Type\r\n                           " +
"     </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 183 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.EmployeeType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Department\r\n                              " +
"  </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 191 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.CurrentDepartment);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Role\r\n                                </td" +
">\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 199 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.Role);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Employment Status\r\n                       " +
"         </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 207 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.EmploymentStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Job Title\r\n                               " +
" </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 215 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.JobTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Pay Grade\r\n                               " +
" </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 223 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.PayGrade);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Shift\r\n                                </t" +
"d>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 231 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.Shift);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Nationality\r\n                             " +
"   </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 239 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.Nationality);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                    Date Of Birth\r\n                           " +
"     </td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 12192), Tuple.Create("\"", 12237)
            
            #line 246 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 12200), Tuple.Create<System.Object, System.Int32>(Model.Details.DateOfBirth.ToString()
            
            #line default
            #line hidden
, 12200), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 247 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.DateOfBirth);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Address Line 1
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 255 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.AddressLine1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Address Line 2
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 263 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.AddressLine2);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Zip Code
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 271 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.ZipCode);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Street
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 279 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.Street);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    City
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 287 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.City);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    State
                                </td>
                                <td>
");

WriteLiteral("                                    ");

            
            #line 295 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(Model.Details.State);

            
            #line default
            #line hidden
WriteLiteral(@"
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Country
                                </td>
                                <td>
                                    <i");

WriteLiteral(" class=\"{{getCountryCode(employee.Country)}} flag\"");

WriteLiteral("></i>");

            
            #line 303 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                        Write(Model.Details.Country);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                   </tbody>\r\n                    </table>\r\n                </div" +
">\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"identification-tab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                Identification Details\r\n            </div>\r\n\r\n            <tab" +
"le");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>Identification Type Code</th>
                        <th>Identification Type Name</th>
                        <th>Identification #</th>
                        <th>Expires On</th>
                    </tr>
                </thead>
                <tbody>
");

            
            #line 326 "..\..\Views\Tasks\Employees\Info.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 326 "..\..\Views\Tasks\Employees\Info.cshtml"
                     foreach (var item in Model.IdentificationDetails)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 329 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.IdentificationTypeCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 330 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.IdentificationTypeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 331 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.IdentificationNumber);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 332 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.ExpiresOn);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 334 "..\..\Views\Tasks\Employees\Info.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 15933), Tuple.Create("\"", 16095)
, Tuple.Create(Tuple.Create("", 15940), Tuple.Create("/dashboard/hrm/tasks/employees/identification-details?View=FormView&EmployeeId=", 15940), true)
            
            #line 337 "..\..\Views\Tasks\Employees\Info.cshtml"
                   , Tuple.Create(Tuple.Create("", 16019), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 16019), false)
, Tuple.Create(Tuple.Create("", 16044), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=identification-tab", 16044), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                Add New\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"social-networks-tab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                Social Networks\r\n            </div>\r\n\r\n            <table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
">Social Network Name</th>\r\n                        <th>Social Network Id</th>\r\n " +
"                   </tr>\r\n                </thead>\r\n                <tbody>\r\n");

            
            #line 354 "..\..\Views\Tasks\Employees\Info.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 354 "..\..\Views\Tasks\Employees\Info.cshtml"
                     foreach (var item in Model.SocialNetworks)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>\r\n                 " +
"               <i");

WriteAttribute("class", Tuple.Create(" class=\"", 16824), Tuple.Create("\"", 16859)
            
            #line 358 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 16832), Tuple.Create<System.Object, System.Int32>(item.SemanticCssClass
            
            #line default
            #line hidden
, 16832), false)
, Tuple.Create(Tuple.Create(" ", 16854), Tuple.Create("icon", 16855), true)
);

WriteLiteral("></i>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16901), Tuple.Create("\"", 16921)
            
            #line 359 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 16908), Tuple.Create<System.Object, System.Int32>(item.BaseUrl
            
            #line default
            #line hidden
, 16908), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 360 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.SocialNetworkName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </td>\r\n      " +
"                      <td>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17143), Tuple.Create("\"", 17166)
            
            #line 364 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 17150), Tuple.Create<System.Object, System.Int32>(item.ProfileUrl
            
            #line default
            #line hidden
, 17150), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 365 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.SocialNetworkId);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n\r\n                            </td>\r\n    " +
"                    </tr>\r\n");

            
            #line 370 "..\..\Views\Tasks\Employees\Info.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17436), Tuple.Create("\"", 17592)
, Tuple.Create(Tuple.Create("", 17443), Tuple.Create("/dashboard/hrm/tasks/employees/social-networks?View=FormView&EmployeeId=", 17443), true)
            
            #line 373 "..\..\Views\Tasks\Employees\Info.cshtml"
            , Tuple.Create(Tuple.Create("", 17515), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 17515), false)
, Tuple.Create(Tuple.Create("", 17540), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=social-networks-tab", 17540), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                Add New\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"experiences-tab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                Experiences\r\n            </div>\r\n\r\n            <table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>Organization Name</th>
                        <th>Title</th>
                        <th>Started On</th>
                        <th>Ended On</th>
                    </tr>
                </thead>
                <tbody>
");

            
            #line 392 "..\..\Views\Tasks\Employees\Info.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 392 "..\..\Views\Tasks\Employees\Info.cshtml"
                     foreach (var item in Model.Experiences)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 395 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.OrganizationName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 396 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteAttribute("title", Tuple.Create(" title=\"", 18458), Tuple.Create("\"", 18487)
            
            #line 397 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 18466), Tuple.Create<System.Object, System.Int32>(item.StartedOn.Value
            
            #line default
            #line hidden
, 18466), false)
);

WriteLiteral(">");

            
            #line 397 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                         Write(item.StartedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteAttribute("title", Tuple.Create(" title=\"", 18562), Tuple.Create("\"", 18589)
            
            #line 398 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 18570), Tuple.Create<System.Object, System.Int32>(item.EndedOn.Value
            
            #line default
            #line hidden
, 18570), false)
);

WriteLiteral(">");

            
            #line 398 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                       Write(item.EndedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 400 "..\..\Views\Tasks\Employees\Info.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18749), Tuple.Create("\"", 18897)
, Tuple.Create(Tuple.Create("", 18756), Tuple.Create("/dashboard/hrm/tasks/employees/experiences?View=FormView&EmployeeId=", 18756), true)
            
            #line 404 "..\..\Views\Tasks\Employees\Info.cshtml"
        , Tuple.Create(Tuple.Create("", 18824), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 18824), false)
, Tuple.Create(Tuple.Create("", 18849), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=experiences-tab", 18849), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                Add New\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"qualifications-tab\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                Qualifications\r\n            </div>\r\n\r\n            <table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>Education Level Name</th>
                        <th>Institution</th>
                        <th>Majors</th>
                        <th>Total Years</th>
                        <th>Started On</th>
                        <th>Completed On</th>
                    </tr>
                </thead>
                <tbody>
");

            
            #line 425 "..\..\Views\Tasks\Employees\Info.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 425 "..\..\Views\Tasks\Employees\Info.cshtml"
                     foreach (var item in Model.Qualifications)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 428 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.EducationLevelName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 429 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.Institution);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 430 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.Majors);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 431 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(item.TotalYears);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteAttribute("title", Tuple.Create(" title=\"", 19986), Tuple.Create("\"", 20015)
            
            #line 432 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 19994), Tuple.Create<System.Object, System.Int32>(item.StartedOn.Value
            
            #line default
            #line hidden
, 19994), false)
);

WriteLiteral(">");

            
            #line 432 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                         Write(item.StartedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td");

WriteAttribute("title", Tuple.Create(" title=\"", 20090), Tuple.Create("\"", 20121)
            
            #line 433 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 20098), Tuple.Create<System.Object, System.Int32>(item.CompletedOn.Value
            
            #line default
            #line hidden
, 20098), false)
);

WriteLiteral(">");

            
            #line 433 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                           Write(item.CompletedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 435 "..\..\Views\Tasks\Employees\Info.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 20285), Tuple.Create("\"", 20439)
, Tuple.Create(Tuple.Create("", 20292), Tuple.Create("/dashboard/hrm/tasks/employees/qualifications?View=FormView&EmployeeId=", 20292), true)
            
            #line 439 "..\..\Views\Tasks\Employees\Info.cshtml"
           , Tuple.Create(Tuple.Create("", 20363), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 20363), false)
, Tuple.Create(Tuple.Create("", 20388), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=qualifications-tab", 20388), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(@">
                Add New
            </a>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("".tabular.menu .item"").tab();

        const tab = window.getQueryStringByName(""data-tab"");

        if (tab) {
            $("".tabular.menu .item"").tab('change tab', tab);
        };
    });
</script>");

        }
    }
}
#pragma warning restore 1591
