#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;

    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Employees/Info.cshtml")]
    public partial class _Views_Tasks_Employees_Info_cshtml : System.Web.Mvc.WebViewPage<MixERP.HRM.ViewModels.EmployeeInfo>
    {
        public _Views_Tasks_Employees_Info_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Employees\Info.cshtml"
  
    ViewBag.Title = "Employee Info " + Model.Details.EmployeeName;
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui attached segment\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui purple header\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 291), Tuple.Create("\"", 374)
, Tuple.Create(Tuple.Create("", 297), Tuple.Create("/dashboard/hrm/services/attachments/", 297), true)
            
            #line 11 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 333), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 333), false)
, Tuple.Create(Tuple.Create("", 353), Tuple.Create("?Width=200&Height=200", 353), true)
);

WriteLiteral("\r\n                     class=\"ui circular image\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 423), Tuple.Create("\"", 456)
            
            #line 12 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 429), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeName
            
            #line default
            #line hidden
, 429), false)
);

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Tasks\Employees\Info.cshtml"
               Write(Model.Details.EmployeeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"sub header\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 16 "..\..\Views\Tasks\Employees\Info.cshtml"
                   Write(Model.Details.EmployeeType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n\r\n   " +
"         <div");

WriteLiteral(" class=\"bpad8\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"/dashboard/hrm/tasks/employees\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Employees</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 928), Tuple.Create("\"", 1025)
, Tuple.Create(Tuple.Create("", 935), Tuple.Create("/dashboard/hrm/tasks/employees/identification-details?EmployeeId=", 935), true)
            
            #line 25 "..\..\Views\Tasks\Employees\Info.cshtml"
              , Tuple.Create(Tuple.Create("", 1000), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1000), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Identification Details</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1101), Tuple.Create("\"", 1191)
, Tuple.Create(Tuple.Create("", 1108), Tuple.Create("/dashboard/hrm/tasks/employees/social-networks?EmployeeId=", 1108), true)
            
            #line 26 "..\..\Views\Tasks\Employees\Info.cshtml"
       , Tuple.Create(Tuple.Create("", 1166), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1166), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Social Networks</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1260), Tuple.Create("\"", 1346)
, Tuple.Create(Tuple.Create("", 1267), Tuple.Create("/dashboard/hrm/tasks/employees/experiences?EmployeeId=", 1267), true)
            
            #line 27 "..\..\Views\Tasks\Employees\Info.cshtml"
   , Tuple.Create(Tuple.Create("", 1321), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1321), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Experiences</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1411), Tuple.Create("\"", 1500)
, Tuple.Create(Tuple.Create("", 1418), Tuple.Create("/dashboard/hrm/tasks/employees/qualifications?EmployeeId=", 1418), true)
            
            #line 28 "..\..\Views\Tasks\Employees\Info.cshtml"
      , Tuple.Create(Tuple.Create("", 1475), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1475), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Qualifications</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1568), Tuple.Create("\"", 1660)
, Tuple.Create(Tuple.Create("", 1575), Tuple.Create("/dashboard/hrm/tasks/employees/leave-application?EmployeeId=", 1575), true)
            
            #line 29 "..\..\Views\Tasks\Employees\Info.cshtml"
         , Tuple.Create(Tuple.Create("", 1635), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 1635), false)
);

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">Leave Application</a>\r\n                </div>\r\n            </div>\r\n\r\n           " +
" <div");

WriteLiteral(" class=\"ui attached tabular menu\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"active item\"");

WriteLiteral(" data-tab=\"general-info-tab\"");

WriteLiteral(">General Information</a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"identification-tab\"");

WriteLiteral(">Identification Details</a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"social-networks-tab\"");

WriteLiteral(">Social Networks</a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"experiences-tab\"");

WriteLiteral(">Experiences</a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-tab=\"qualifications-tab\"");

WriteLiteral(">Qualifications</a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui active tab attached segment\"");

WriteLiteral(" data-tab=\"general-info-tab\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"five wide column\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ui segment\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ui large header\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 45 "..\..\Views\Tasks\Employees\Info.cshtml"
                           Write(Model.Details.EmployeeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2674), Tuple.Create("\"", 2737)
, Tuple.Create(Tuple.Create("", 2681), Tuple.Create("/dashboard/hrm/services/attachments/", 2681), true)
            
            #line 47 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2717), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 2717), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2793), Tuple.Create("\"", 2876)
, Tuple.Create(Tuple.Create("", 2799), Tuple.Create("/dashboard/hrm/services/attachments/", 2799), true)
            
            #line 48 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2835), Tuple.Create<System.Object, System.Int32>(Model.Details.Photo
            
            #line default
            #line hidden
, 2835), false)
, Tuple.Create(Tuple.Create("", 2855), Tuple.Create("?Height=300&Width=272", 2855), true)
);

WriteLiteral(" class=\"ui image\"");

WriteAttribute("alt", Tuple.Create("\r\n                                     alt=\"", 2894), Tuple.Create("\"", 2965)
            
            #line 49 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 2938), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeName
            
            #line default
            #line hidden
, 2938), false)
);

WriteLiteral(" />\r\n                            </a>\r\n                            <br />\r\n      " +
"                      <table");

WriteLiteral(" class=\"ui striped definition table\"");

WriteLiteral(@">
                                <tbody>
                                    <tr>
                                        <td>
                                            Email Address
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"mail icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3512), Tuple.Create("\"", 3553)
, Tuple.Create(Tuple.Create("", 3519), Tuple.Create("mailto:", 3519), true)
            
            #line 60 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 3526), Tuple.Create<System.Object, System.Int32>(Model.Details.EmailAddress
            
            #line default
            #line hidden
, 3526), false)
);

WriteLiteral(">");

            
            #line 60 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                    Write(Model.Details.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Website
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"world icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4030), Tuple.Create("\"", 4059)
            
            #line 69 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 4037), Tuple.Create<System.Object, System.Int32>(Model.Details.Website
            
            #line default
            #line hidden
, 4037), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                        Write(Model.Details.Website);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Blog
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"world icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4544), Tuple.Create("\"", 4570)
            
            #line 78 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 4551), Tuple.Create<System.Object, System.Int32>(Model.Details.Blog
            
            #line default
            #line hidden
, 4551), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                     Write(Model.Details.Blog);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Home Phone
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"phone icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5058), Tuple.Create("\"", 5093)
, Tuple.Create(Tuple.Create("", 5065), Tuple.Create("tel:", 5065), true)
            
            #line 87 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 5069), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneHome
            
            #line default
            #line hidden
, 5069), false)
);

WriteLiteral(">");

            
            #line 87 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                              Write(Model.Details.PhoneHome);

            
            #line default
            #line hidden
WriteLiteral(@"</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Cell Phone
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"mobile icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5573), Tuple.Create("\"", 5608)
, Tuple.Create(Tuple.Create("", 5580), Tuple.Create("tel:", 5580), true)
            
            #line 97 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 5584), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneCell
            
            #line default
            #line hidden
, 5584), false)
);

WriteLiteral(">");

            
            #line 97 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                              Write(Model.Details.PhoneCell);

            
            #line default
            #line hidden
WriteLiteral(@"</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Phone (Office Extension)
                                        </td>
                                        <td>
                                            <i");

WriteLiteral(" class=\"phone icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6101), Tuple.Create("\"", 6147)
, Tuple.Create(Tuple.Create("", 6108), Tuple.Create("tel:", 6108), true)
            
            #line 107 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 6112), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneOfficeExtension
            
            #line default
            #line hidden
, 6112), false)
);

WriteLiteral(">");

            
            #line 107 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                         Write(Model.Details.PhoneOfficeExtension);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                                        </td>\r\n                          " +
"          </tr>\r\n                                    <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                        <td>\r\n                                " +
"            Emergency Phone\r\n                                        </td>\r\n    " +
"                                    <td>\r\n                                      " +
"      <i");

WriteLiteral(" class=\"red phone icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6663), Tuple.Create("\"", 6703)
, Tuple.Create(Tuple.Create("", 6670), Tuple.Create("tel:", 6670), true)
            
            #line 117 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 6674), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneEmergency
            
            #line default
            #line hidden
, 6674), false)
);

WriteLiteral(">");

            
            #line 117 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                   Write(Model.Details.PhoneEmergency);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </td>\r\n                            " +
"        </tr>\r\n                                    <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                        <td>\r\n                                " +
"            Emergency Phone 2\r\n                                        </td>\r\n  " +
"                                      <td>\r\n                                    " +
"        <i");

WriteLiteral(" class=\"red phone icon\"");

WriteLiteral("></i>\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7213), Tuple.Create("\"", 7254)
, Tuple.Create(Tuple.Create("", 7220), Tuple.Create("tel:", 7220), true)
            
            #line 126 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 7224), Tuple.Create<System.Object, System.Int32>(Model.Details.PhoneEmergency2
            
            #line default
            #line hidden
, 7224), false)
);

WriteLiteral(">");

            
            #line 126 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                    Write(Model.Details.PhoneEmergency2);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </td>\r\n                            " +
"        </tr>\r\n                                    <tr>\r\n                       " +
"                 <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                            User\r\n                            " +
"            </td>\r\n                                        <td>\r\n               " +
"                             <i");

WriteLiteral(" class=\"user icon\"");

WriteLiteral("></i>\r\n");

WriteLiteral("                                            ");

            
            #line 135 "..\..\Views\Tasks\Employees\Info.cshtml"
                                       Write(Model.Details.UserName);

            
            #line default
            #line hidden
WriteLiteral(@"
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                    <div");

WriteLiteral(" class=\"eleven wide column\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" class=\"ui striped definition table\"");

WriteLiteral(">\r\n                            <tbody>\r\n                                <tr>\r\n   " +
"                                 <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Joined On\r\n                           " +
"         </td>\r\n                                    <td");

WriteAttribute("title", Tuple.Create(" title=\"", 8402), Tuple.Create("\"", 8444)
            
            #line 150 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 8410), Tuple.Create<System.Object, System.Int32>(Model.Details.JoinedOn.ToString()
            
            #line default
            #line hidden
, 8410), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 151 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.JoinedOn);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Office\r\n                              " +
"      </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 159 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.Office);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Gender\r\n                              " +
"      </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 167 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.GenderName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Marital Status\r\n                      " +
"              </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 175 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.MaritalStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Employee Type\r\n                       " +
"             </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 183 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.EmployeeType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Department\r\n                          " +
"          </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 191 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.CurrentDepartment);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Role\r\n                                " +
"    </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 199 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.Role);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr");

WriteLiteral(" class=\"negative\"");

WriteLiteral(">\r\n                                    <td");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Employment Status\r\n                   " +
"                 </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 207 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.EmploymentStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Job Title\r\n                           " +
"         </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 215 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.JobTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Pay Grade\r\n                           " +
"         </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 223 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.PayGrade);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Shift\r\n                               " +
"     </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 231 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.Shift);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Nationality\r\n                         " +
"           </td>\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 239 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.Nationality);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                                <tr>\r\n                                    <td" +
"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">\r\n                                        Date Of Birth\r\n                       " +
"             </td>\r\n                                    <td");

WriteAttribute("title", Tuple.Create(" title=\"", 13113), Tuple.Create("\"", 13158)
            
            #line 246 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 13121), Tuple.Create<System.Object, System.Int32>(Model.Details.DateOfBirth.ToString()
            
            #line default
            #line hidden
, 13121), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 247 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.DateOfBirth);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Address Line 1
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 255 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.AddressLine1);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Address Line 2
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 263 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.AddressLine2);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Zip Code
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 271 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.ZipCode);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Street
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 279 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.Street);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        City
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 287 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.City);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        State
                                    </td>
                                    <td>
");

WriteLiteral("                                        ");

            
            #line 295 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(Model.Details.State);

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Country
                                    </td>
                                    <td>
                                        <i");

WriteLiteral(" class=\"{{getCountryCode(employee.Country)}} flag\"");

WriteLiteral("></i>");

            
            #line 303 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                                                            Write(Model.Details.Country);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                            </tbody>\r\n                        </table>\r\n     " +
"               </div>\r\n                </div>\r\n            </div>\r\n            <" +
"div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"identification-tab\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                    Identification Details\r\n                </div>\r\n\r\n        " +
"        <table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Identification Type Code</th>
                            <th>Identification Type Name</th>
                            <th>Identification #</th>
                            <th>Expires On</th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 326 "..\..\Views\Tasks\Employees\Info.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 326 "..\..\Views\Tasks\Employees\Info.cshtml"
                         foreach (var item in Model.IdentificationDetails)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 329 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.IdentificationTypeCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 330 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.IdentificationTypeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 331 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.IdentificationNumber);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 332 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.ExpiresOn);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");

            
            #line 334 "..\..\Views\Tasks\Employees\Info.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17214), Tuple.Create("\"", 17376)
, Tuple.Create(Tuple.Create("", 17221), Tuple.Create("/dashboard/hrm/tasks/employees/identification-details?View=FormView&EmployeeId=", 17221), true)
            
            #line 337 "..\..\Views\Tasks\Employees\Info.cshtml"
                       , Tuple.Create(Tuple.Create("", 17300), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 17300), false)
, Tuple.Create(Tuple.Create("", 17325), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=identification-tab", 17325), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                    Add New\r\n                </a>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"social-networks-tab\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                    Social Networks\r\n                </div>\r\n\r\n               " +
" <table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Social Network Name</th>
                            <th>Social Network Id</th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 354 "..\..\Views\Tasks\Employees\Info.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 354 "..\..\Views\Tasks\Employees\Info.cshtml"
                         foreach (var item in Model.SocialNetworks)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>\r\n         " +
"                           <i");

WriteAttribute("class", Tuple.Create(" class=\"", 18185), Tuple.Create("\"", 18220)
            
            #line 358 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 18193), Tuple.Create<System.Object, System.Int32>(item.SemanticCssClass
            
            #line default
            #line hidden
, 18193), false)
, Tuple.Create(Tuple.Create(" ", 18215), Tuple.Create("icon", 18216), true)
);

WriteLiteral("></i>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18266), Tuple.Create("\"", 18286)
            
            #line 359 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 18273), Tuple.Create<System.Object, System.Int32>(item.BaseUrl
            
            #line default
            #line hidden
, 18273), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 360 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(item.SocialNetworkName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </td>" +
"\r\n                                <td>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18528), Tuple.Create("\"", 18551)
            
            #line 364 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 18535), Tuple.Create<System.Object, System.Int32>(item.ProfileUrl
            
            #line default
            #line hidden
, 18535), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 365 "..\..\Views\Tasks\Employees\Info.cshtml"
                                   Write(item.SocialNetworkId);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n\r\n                                </t" +
"d>\r\n                            </tr>\r\n");

            
            #line 370 "..\..\Views\Tasks\Employees\Info.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18853), Tuple.Create("\"", 19009)
, Tuple.Create(Tuple.Create("", 18860), Tuple.Create("/dashboard/hrm/tasks/employees/social-networks?View=FormView&EmployeeId=", 18860), true)
            
            #line 373 "..\..\Views\Tasks\Employees\Info.cshtml"
                , Tuple.Create(Tuple.Create("", 18932), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 18932), false)
, Tuple.Create(Tuple.Create("", 18957), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=social-networks-tab", 18957), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                    Add New\r\n                </a>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"experiences-tab\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                    Experiences\r\n                </div>\r\n\r\n                <ta" +
"ble");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Organization Name</th>
                            <th>Title</th>
                            <th>Started On</th>
                            <th>Ended On</th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 392 "..\..\Views\Tasks\Employees\Info.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 392 "..\..\Views\Tasks\Employees\Info.cshtml"
                         foreach (var item in Model.Experiences)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 395 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.OrganizationName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 396 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 19967), Tuple.Create("\"", 19996)
            
            #line 397 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 19975), Tuple.Create<System.Object, System.Int32>(item.StartedOn.Value
            
            #line default
            #line hidden
, 19975), false)
);

WriteLiteral(">");

            
            #line 397 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                             Write(item.StartedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 20075), Tuple.Create("\"", 20102)
            
            #line 398 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 20083), Tuple.Create<System.Object, System.Int32>(item.EndedOn.Value
            
            #line default
            #line hidden
, 20083), false)
);

WriteLiteral(">");

            
            #line 398 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                           Write(item.EndedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");

            
            #line 400 "..\..\Views\Tasks\Employees\Info.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 20282), Tuple.Create("\"", 20430)
, Tuple.Create(Tuple.Create("", 20289), Tuple.Create("/dashboard/hrm/tasks/employees/experiences?View=FormView&EmployeeId=", 20289), true)
            
            #line 404 "..\..\Views\Tasks\Employees\Info.cshtml"
            , Tuple.Create(Tuple.Create("", 20357), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 20357), false)
, Tuple.Create(Tuple.Create("", 20382), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=experiences-tab", 20382), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(">\r\n                    Add New\r\n                </a>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"ui tab attached segment\"");

WriteLiteral(" data-tab=\"qualifications-tab\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui grey header\"");

WriteLiteral(">\r\n                    Qualifications\r\n                </div>\r\n\r\n                " +
"<table");

WriteLiteral(" class=\"ui striped table\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Education Level Name</th>
                            <th>Institution</th>
                            <th>Majors</th>
                            <th>Total Years</th>
                            <th>Started On</th>
                            <th>Completed On</th>
                        </tr>
                    </thead>
                    <tbody>
");

            
            #line 425 "..\..\Views\Tasks\Employees\Info.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 425 "..\..\Views\Tasks\Employees\Info.cshtml"
                         foreach (var item in Model.Qualifications)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 428 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.EducationLevelName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 429 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.Institution);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 430 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.Majors);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 431 "..\..\Views\Tasks\Employees\Info.cshtml"
                               Write(item.TotalYears);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 21627), Tuple.Create("\"", 21656)
            
            #line 432 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 21635), Tuple.Create<System.Object, System.Int32>(item.StartedOn.Value
            
            #line default
            #line hidden
, 21635), false)
);

WriteLiteral(">");

            
            #line 432 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                             Write(item.StartedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 21735), Tuple.Create("\"", 21766)
            
            #line 433 "..\..\Views\Tasks\Employees\Info.cshtml"
, Tuple.Create(Tuple.Create("", 21743), Tuple.Create<System.Object, System.Int32>(item.CompletedOn.Value
            
            #line default
            #line hidden
, 21743), false)
);

WriteLiteral(">");

            
            #line 433 "..\..\Views\Tasks\Employees\Info.cshtml"
                                                               Write(item.CompletedOn.Value.ToLocalTime());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");

            
            #line 435 "..\..\Views\Tasks\Employees\Info.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 21950), Tuple.Create("\"", 22104)
, Tuple.Create(Tuple.Create("", 21957), Tuple.Create("/dashboard/hrm/tasks/employees/qualifications?View=FormView&EmployeeId=", 21957), true)
            
            #line 439 "..\..\Views\Tasks\Employees\Info.cshtml"
               , Tuple.Create(Tuple.Create("", 22028), Tuple.Create<System.Object, System.Int32>(Model.Details.EmployeeId
            
            #line default
            #line hidden
, 22028), false)
, Tuple.Create(Tuple.Create("", 22053), Tuple.Create("&ReturnUrl={{thispage}}&data-tab=qualifications-tab", 22053), true)
);

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(@">
                    Add New
                </a>
            </div>
        </div>
</div>
<script>
    $(document).ready(function () {
        $("".tabular.menu .item"").tab();

        var tab = window.getQueryStringByName(""data-tab"");

        if (tab) {
            $("".tabular.menu .item"").tab('change tab', tab);
        };
    });
</script>");

        }
    }
}
#pragma warning restore 1591
