#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/EmploymentStatuses/Index.cshtml")]
    public partial class _Views_Setup_EmploymentStatuses_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_EmploymentStatuses_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\EmploymentStatuses\Index.cshtml"
  
    ViewBag.Title = "Employment Statuses";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"Emp" +
"loyment Statuses\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/hrm/employment-stat" +
"uses\";\r\n    scrudFactory.viewTableName = \"hrm.employment_statuses\";\r\n\r\n    scrud" +
"Factory.formAPI = \"/api/forms/hrm/employment-statuses\";\r\n    scrudFactory.formTa" +
"bleName = \"hrm.employment_statuseses\";\r\n\r\n    scrudFactory.excludedColumns = [\"A" +
"uditUserId\", \"AuditTs\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFacto" +
"ry.allowEdit = true;\r\n\r\n    scrudFactory.live = \"EmploymentStatusName\";\r\n\r\n    s" +
"crudFactory.card = {\r\n        header: \"employment_status_name\",\r\n        meta: \"" +
"employment_status_code\",\r\n        description: \"is_contract\"\r\n    };\r\n\r\n    scru" +
"dFactory.layout = [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n   " +
"             [\"EmploymentStatusId\"],\r\n                [\"EmploymentStatusCode\", \"" +
"EmploymentStatusName\"],\r\n                [\"IsContract\", \"DefaultEmploymentStatus" +
"CodeId\"],\r\n                [\"Description\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n" +
"    scrudFactory.keys = [\r\n        {\r\n            property: \"DefaultEmploymentSt" +
"atusCodeId\",\r\n            url: \'/api/forms/hrm/employment-status-codes/display-f" +
"ields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n            te" +
"xtField: \"Value\"\r\n        }\r\n    ];\r\n\r\n    $.get(\'/ScrudFactory/View.html\', func" +
"tion (view) {\r\n        $.get(\'/ScrudFactory/Form.html\', function (form) {\r\n     " +
"       $(\"#ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFactoryForm\").ht" +
"ml(form);\r\n            $.cachedScript(\"/assets/js/scrudfactory-view.js\");\r\n     " +
"       $.cachedScript(\"/assets/js/scrudfactory-form.js\");\r\n        });\r\n    });\r" +
"\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
