#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.HRM;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/OfficeHours/Index.cshtml")]
    public partial class _Views_Setup_OfficeHours_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_OfficeHours_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\OfficeHours\Index.cshtml"
  
    ViewBag.Title = "Office Hours";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title =  \"Of" +
"fice Hours\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/hrm/office-hour-scrud-vie" +
"w\";\r\n    scrudFactory.viewTableName = \"hrm.office_hour_scrud_view\";\r\n\r\n    scrud" +
"Factory.formAPI = \"/api/forms/hrm/office-hours\";\r\n    scrudFactory.formTableName" +
" = \"hrm.office_hours\";\r\n\r\n    scrudFactory.excludedColumns = [\"AuditUserId\", \"Au" +
"ditTs\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFactory.allowEdit = t" +
"rue;\r\n\r\n    scrudFactory.live = \"OfficeHourName\";\r\n\r\n    scrudFactory.keys = [\r\n" +
"        {\r\n            property: \"OfficeId\",\r\n            url: \'/api/forms/core/" +
"offices/display-fields\',\r\n            data: null,\r\n            valueField: \"Key\"" +
",\r\n            textField: \"Value\"\r\n        },\r\n        {\r\n            property: " +
"\"ShiftId\",\r\n            url: \'/api/forms/hrm/shifts/display-fields\',\r\n          " +
"  data: null,\r\n            valueField: \"Key\",\r\n            textField: \"Value\"\r\n " +
"       },\r\n        {\r\n            property: \"WeekDayId\",\r\n            url: \'/api" +
"/forms/hrm/week-days/display-fields\',\r\n            data: null,\r\n            valu" +
"eField: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n    $.get(\'/S" +
"crudFactory/View.html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.htm" +
"l\', function (form) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n         " +
"   $(\"#ScrudFactoryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/sc" +
"rudfactory-view.js\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form." +
"js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>\r\n");

        }
    }
}
#pragma warning restore 1591
